version: "2.15.1"
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  timescale:
     image: timescale/timescaledb-ha:pg14-latest 

volumes:
  db:
    driver: local

#docker run -d --name timescaledb -p 5432:5432 -e POSTGRES_PASSWORD=password timescale/timescaledb-ha:pg14-latest
#
#docker run -d --name timescaledb -p 127.0.0.1:5432:5432 \
#-e POSTGRES_PASSWORD=password timescale/timescaledb-ha:pg14-latest
#
#docker exec -it timescaledb psql -U postgres
#
#docker run -d --name timescaledb -p 5432:5432 \
#-v /your/data/dir:/home/postgres/pgdata/data \
#-e POSTGRES_PASSWORD=password timescale/timescaledb-ha:pg14-latest
#
#psql -U postgres -h localhost
#
#CREATE database example;
#
#\c example
#
#CREATE EXTENSION IF NOT EXISTS timescaledb;
#
#
#psql -U postgres -h localhost -d example
#
#
#tsdb=> \dx
#
#tutorial for timescale
