# This is a basic workflow to help you get started with Actions

name: learn-github-actions

# Controls when the workflow will run
on: [push]
jobs:
  # This workflow contains a single job called "build"
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      # Runs a set of commands using the runners shell
      - run: npm install -g bats
      - run: bats -v
